# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import qdarkstyle
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenStreamDeck(object):
    def setupUi(self, OpenStreamDeck):
        OpenStreamDeck.setObjectName("OpenStreamDeck")
        OpenStreamDeck.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(OpenStreamDeck)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 50, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label.setObjectName("label")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(170, 190, 256, 192))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        OpenStreamDeck.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(OpenStreamDeck)
        self.statusbar.setObjectName("statusbar")
        OpenStreamDeck.setStatusBar(self.statusbar)

        self.retranslateUi(OpenStreamDeck)
        QtCore.QMetaObject.connectSlotsByName(OpenStreamDeck)

    def retranslateUi(self, OpenStreamDeck):
        _translate = QtCore.QCoreApplication.translate
        OpenStreamDeck.setWindowTitle(_translate("OpenStreamDeck", "Open Stream Deck"))
        self.pushButton.setText(_translate("OpenStreamDeck", "PushButton"))
        self.label.setText(_translate("OpenStreamDeck", "TextLabel"))
        self.treeWidget.headerItem().setText(0, _translate("OpenStreamDeck", "1"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("OpenStreamDeck", "test"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("OpenStreamDeck", "test"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("OpenStreamDeck", "test"))
        self.treeWidget.topLevelItem(1).child(0).child(0).setText(0, _translate("OpenStreamDeck", "test"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("OpenStreamDeck", "test"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    OpenStreamDeck = QtWidgets.QMainWindow()
    ui = Ui_OpenStreamDeck()
    ui.setupUi(OpenStreamDeck)
    OpenStreamDeck.show()
    sys.exit(app.exec_())
